### ISSUE TITLE
Character encoding going awry between GIT and the site

### ISSUE THREAD

**Issue by charlesrr** [restlessmedia/oakporchesuk.co.uk#5]
Hi Phil

When I uploaded text files from the blogs in google docs to GIT, some characters looked odd on the website. For example you’re came through as youâ€™re. I tried changing it to you're instead (non-curly apostrophe), but it didn't help. For now, I've changed them all to "you are" instead, but it was quite time consuming. Perhaps the database table is not set as utf-8 or something (I'm not an expert in this area - I just remember creating vbulletin tables and had to get the character encoding correct otherwise the whole site would have stuff like that).

Any ideas?

**Comment by restlessmedia** [comment]
Not sure, I’ll check in the morning - should be a simple fix.

On 14 Sep 2020, at 14:38, charlesrr <notifications@github.com> wrote:

﻿

Hi Phil

When I uploaded text files from the blogs in google docs to GIT, some characters looked odd on the website. For example you’re came through as youâ€™re. I tried changing it to you're instead (non-curly apostrophe), but it didn't help. For now, I've changed them all to "you are" instead, but it was quite time consuming. Perhaps the database table is not set as utf-8 or something (I'm not an expert in this area - I just remember creating vbulletin tables and had to get the character encoding correct otherwise the whole site would have stuff like that).

Any ideas?

**Comment by restlessmedia** [comment]
Hey,

I’ve just checked and this existing one appears to be working ok with apostrophes:

https://github.com/restlessmedia/oakporchesuk.co.uk/blob/master/docs/blog-2019-10-01.md
https://www.monarchoak.co.uk/blog/read/?title=4%20Oak%20Framed%20Buildings%20Options%20to%20Enhance%20your%20Home
![Capture](https://user-images.githubusercontent.com/694576/93913570-2ff91580-fcfd-11ea-97a6-4172b40ebfbc.PNG)


Phil

**Comment by charlesrr** [comment]
Weird. Is it something about the way I'm uploading the files? I'm using notepad++ to create utf-8 encoded .md files. However, it was happening on a few others that I hadn't uploaded but went back and "fixed".
Here's another one that isn't working (that I didn't make) - https://www.monarchoak.co.uk/blog/read/?title=Do%20I%20need%20planning%20permission%20for%20oak%20gazebos%20and%20garages%3F In GIT, there are characters that appear as metres squared: e.g. "15m²" but on the website, they appear like "15mÂ²"

**Comment by charlesrr** [comment]
This is still an issue.
It's not just the blog posts that have broken character encoding on Monarch Oak. URLs are messed up too, for example: https://www.monarchoak.co.uk/blog/read/?title=Timber%20Framed%20Garage%20Kits%3A%20to%20fit%20or%20not%20to%20fit%3F I don't know how to fix it. Last time, I created the file within github editor itself, pasting the text in without any formatting, rather than uploading a file created locally. That didn't make any difference.

**Comment by restlessmedia** [comment]
Yep, ok - taking a look now.

On 16 Nov 2020, at 11:25, charlesrr <notifications@github.com> wrote:

﻿

This is still an issue.
It's not just the blog posts that have broken character encoding on Monarch Oak. URLs are messed up too, for example: https://www.monarchoak.co.uk/blog/read/?title=Timber%20Framed%20Garage%20Kits%3A%20to%20fit%20or%20not%20to%20fit%3F<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.monarchoak.co.uk%2Fblog%2Fread%2F%3Ftitle%3DTimber%2520Framed%2520Garage%2520Kits%253A%2520to%2520fit%2520or%2520not%2520to%2520fit%253F&data=04%7C01%7C%7C1034a8d75d0949ce28b308d88a225908%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637411227405582656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NMywPnAtRbv8UQ0QgHNUGrjSzBGuAscMEVel%2BVuMJnc%3D&reserved=0> I don't know how to fix it. Last time, I created the file within github editor itself, pasting the text in without any formatting, rather than uploading a file created locally. That didn't make any difference.

**Comment by restlessmedia** [comment]
This should be fixed now.
